# Generated by Django 5.0.4 on 2024-06-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0002_alter_account_options_virement_virementdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Virement',
            new_name='CollectionOperation',
        ),
        migrations.RenameModel(
            old_name='VirementDetail',
            new_name='CollectionOperationDetail',
        ),
    ]
