# Generated by Django 5.0.4 on 2024-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0007_collectionoperation_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementoperation',
            name='type',
            field=models.CharField(choices=[('frais', 'Frais'), ('operation', 'Operation')], default='operation', max_length=255),
        ),
    ]
