# Generated by Django 5.0.4 on 2024-06-28 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0008_disbursementoperation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionoperationdetail',
            old_name='banq_number',
            new_name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='collectionoperation',
            name='account',
        ),
        migrations.AddField(
            model_name='collectionoperationdetail',
            name='destination_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tresor.account'),
            preserve_default=False,
        ),
    ]
