# Generated by Django 5.0.4 on 2024-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0009_rename_banq_number_collectionoperationdetail_cheque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionoperation',
            name='type',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('versement', 'Versement'), ('operation', 'Operation')], default='operation', max_length=255),
        ),
    ]
