# Generated by Django 5.0.4 on 2024-07-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0013_disbursementoperation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionoperation',
            name='ref',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='disbursementoperation',
            name='ref',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
