# Generated by Django 5.0.4 on 2024-07-03 23:34

from django.db import migrations

def update_ref_suffix(apps, schema_editor):
    collections = apps.get_model('tresor', 'CollectionOperation')
    for obj in collections.objects.filter(ref__endswith='DTNCR'):
        new_ref = obj.ref[:-5] + 'DTNDB'
        obj.ref = new_ref
        obj.save()
    
    disbursements = apps.get_model('tresor', 'DisbursementOperation')
    for obj in disbursements.objects.filter(ref__endswith='DTNCR'):
        new_ref = obj.ref[:-5] + 'DTNDB'
        obj.ref = new_ref
        obj.save()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0014_alter_collectionoperation_ref_and_more'),
    ]

    operations = [
        migrations.RunPython(update_ref_suffix),
    ]
