# Generated by Django 5.0.4 on 2024-07-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0016_vault_vaultdeposit_vaultwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('can_fund_transfer', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='vault',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tresor.vaultgroup'),
            preserve_default=False,
        ),
    ]
