# Generated by Django 5.0.4 on 2024-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0017_vaultgroup_vault_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='account_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
