# Generated by Django 5.0.4 on 2024-07-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0019_rename_account_number_vault_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultdeposit',
            name='versement_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
