# Generated by Django 5.0.4 on 2024-07-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0020_vaultdeposit_versement_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultdeposit',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='tresor.vault'),
        ),
        migrations.AlterField(
            model_name='vaultwithdrawal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_transfers', to='tresor.account'),
        ),
        migrations.AlterField(
            model_name='vaultwithdrawal',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='tresor.vault'),
        ),
    ]
