# Generated by Django 5.0.4 on 2024-07-10 12:28

import django.utils.timezone
from django.db import migrations, models

def set_date_to_created_at(apps, schema_editor):
    VaultDeposit = apps.get_model('tresor', 'VaultDeposit')
    VaultWithdrawal = apps.get_model('tresor', 'VaultWithdrawal')

    for deposit in VaultDeposit.objects.all():
        deposit.date = deposit.created_at.date()
        deposit.save()

    for withdrawal in VaultWithdrawal.objects.all():
        withdrawal.date = withdrawal.created_at.date()
        withdrawal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0021_alter_vaultdeposit_vault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultdeposit',
            name='date',
            field=models.DateField(default='2024-07-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaultdeposit',
            name='ref',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vaultwithdrawal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaultwithdrawal',
            name='ref',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunPython(set_date_to_created_at),
    ]
