# Generated by Django 5.0.4 on 2024-07-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0022_vaultdeposit_date_vaultdeposit_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to='tresor.vaultgroup'),
        ),
    ]
