# Generated by Django 5.0.4 on 2025-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresor', '0026_alter_vaultwithdrawal_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectionoperationdetail',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='disbursementoperationdetail',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vault',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vaultdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vaultwithdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
