# Generated by Django 5.0.4 on 2024-07-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accounts_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_vaults_access',
            field=models.BooleanField(default=False),
        ),
    ]
