# Generated by Django 5.0.4 on 2024-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_has_accounts_access_user_has_vaults_access'),
        ('tresor', '0021_alter_vaultdeposit_vault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_vault_groups',
            field=models.ManyToManyField(related_name='assigned_users', to='tresor.vaultgroup'),
        ),
    ]
