# Generated by Django 5.0.4 on 2024-07-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_assigned_vault_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_vaults_access',
        ),
    ]
